version: "3"
services:
  database:
    image: "mongo"
    container_name: "mongo"
    environment:
      - MONGO_INITDB_DATABASE.skibble
      - MONGO_INITDB_ROOT_USERNAME.root
      - MONGO_INITDB_ROOT_PASSWORD=
    volumes: 
      - ./mongo-volume:/data/db
    ports:
      - "27017:27017"
